name: Richard Hoyos
collections:
    githubpages:
        label: "Github Pages"
        relative_directory: /githubpages/
        output: true
        permalink: /:collection/:name
    ruby:
        label: "Ruby"
        relative_directory: /ruby/
        output: true
        permalink: /:collection/:name
markdown: kramdown